// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFRCxCeVFH12C6fvQAzv1vXo2uUe8lZjU',
    appId: '1:1077288027529:web:c9df0ee77995207cba8d58',
    messagingSenderId: '1077288027529',
    projectId: 'basi-go',
    authDomain: 'basi-go.firebaseapp.com',
    storageBucket: 'basi-go.firebasestorage.app',
    measurementId: 'G-CBX129D5N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7J10NW3SgDEnKRt_XwMVxmpLaEqBD4q4',
    appId: '1:1077288027529:android:0b4da4bd16277567ba8d58',
    messagingSenderId: '1077288027529',
    projectId: 'basi-go',
    storageBucket: 'basi-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy350JOcuM3shpTGSxi-dl6fa5wLgVZgY',
    appId: '1:1077288027529:ios:e13c473dd7e38a5aba8d58',
    messagingSenderId: '1077288027529',
    projectId: 'basi-go',
    storageBucket: 'basi-go.firebasestorage.app',
    iosBundleId: 'com.example.basigoIncidentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy350JOcuM3shpTGSxi-dl6fa5wLgVZgY',
    appId: '1:1077288027529:ios:e13c473dd7e38a5aba8d58',
    messagingSenderId: '1077288027529',
    projectId: 'basi-go',
    storageBucket: 'basi-go.firebasestorage.app',
    iosBundleId: 'com.example.basigoIncidentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFRCxCeVFH12C6fvQAzv1vXo2uUe8lZjU',
    appId: '1:1077288027529:web:c5ce92f989322ed8ba8d58',
    messagingSenderId: '1077288027529',
    projectId: 'basi-go',
    authDomain: 'basi-go.firebaseapp.com',
    storageBucket: 'basi-go.firebasestorage.app',
    measurementId: 'G-EXWY0S99VV',
  );
}
